server:
  port: 8080
mybatis: # 所有的mapper映射文件
  mapper-locations: classpath:mapping/*.xml

spring: #spring.profiles.active 不同环境下的不同配置
  application:
    name: springcloud-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root
    password: root
#  security:
#    user:
#      name: admin  # 认证用户名
#      password: enjoy  # 认证密码
#      roles:
#       - USER # 授权角色
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #服务注册到eurake里Status下的名称
    prefer-ip-address: true #如果只是配置了prefer-ip-address=true，不配置instance-id那还是显示 hostname，但IP地址是可以访问的。
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）