server:
  port: 8081
spring:
  application:
    name: springcloud-consumer
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #服务注册到eurake里Status下的名称
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
